### ISSUE TITLE
Example 3 fails

### ISSUE THREAD

**Issue by malaire** [mpizenberg/elm-pubgrub#3]
After adding debug check (PR https://github.com/mpizenberg/elm-pubgrub/pull/2) Example 3 fails with following output:
```
> import PubGrub
> import Version
> PubGrub.solve "root" Version.one

Add the following 1 incompatibilities from dependencies of root: ""
   root: 1.0.0, foo: Not ( 1.0.0 <= v )  <<<  from dependency of root at version 1.0.0: ""
Decision level 1 : root : 1.0.0: ""
Derivation : foo : 1.0.0 <= v: ""
Add the following 1 incompatibilities from dependencies of foo: ""
   foo: 2.0.0, bar: Not ( 1.0.0 <= v < 2.0.0 )  <<<  from dependency of foo at version 2.0.0: ""
Decision level 2 : foo : 2.0.0: ""
Derivation : bar : 1.0.0 <= v < 2.0.0: ""
Add the following 1 incompatibilities from dependencies of bar: ""
   bar: 1.0.0, foo: Not ( 1.0.0 <= v < 2.0.0 )  <<<  from dependency of bar at version 1.0.0: ""
Decision level 3 : bar : 1.0.0: ""
Derivation : bar : Not ( 1.0.0 ): ""

Err ("priorCause relation to partialSolution is Satisfies, expected AlmostSatisfies @ PubGrub.continueResolution")
```

Comparing this to [the exact steps algorithm should take](https://github.com/dart-lang/pub/blob/master/doc/solver.md#performing-conflict-resolution):
- `elm-pubgrub` uses incorrect decision level numbers
- at Step 4 first term should be `foo >=2.0.0` but `elm-pubgrub` has `foo 2.0.0`

**Comment by mpizenberg** [comment]
Thanks for all this @malaire ! I'll join the effort as soon as I can take some time, before weekend if I can, in the weekend otherwise.

**Comment by malaire** [comment]
I think I've found a bug in `PubGrub.makeDecision`:

When a version is picked by `pickPackageVersion`, that picked version is then used as first Term in `depIncompats`. For example in this Example 3 version `2.0.0` of `foo` is picked, and then `depIncompats` has `foo 2.0.0` as first Term.

```
...
Add the following 1 incompatibilities from dependencies of foo: ""
   foo: 2.0.0, bar: Not ( 1.0.0 <= v < 2.0.0 )  <<<  from dependency of foo at version 2.0.0: ""
...
```

BUT that is incorrect because PubGrub algorithm description says in [Decision Making](https://github.com/dart-lang/pub/blob/master/doc/solver.md#decision-making) that:

> Pubgrub collapses identical dependencies from adjacent package versions into individual incompatibilities. This substantially reduces the total number of incompatibilities and makes it much easier for Pubgrub to reason about multiple versions of packages at once. For example, rather than representing `foo 1.0.0 depends on bar ^1.0.0` and `foo 1.1.0 depends on bar ^1.0.0` as two separate incompatibilities, they're collapsed together into the single incompatibility `{foo ^1.0.0, not bar ^1.0.0}`.
> The version ranges of the dependers (`foo` in the example above) always have an inclusive lower bound of the first version that has the dependency, and an exclusive upper bound of the first package that doesn't have the dependency. if the last published version of the package has the dependency, the upper bound is omitted (as in `foo >=1.0.0`); similarly, if the first published version of the package has the dependency, the lower bound is omitted (as in `foo <2.0.0`). Expanding the version range in this way makes it more closely match the format users tend to use when authoring dependencies, which makes it easier for Pubgrub to reason efficiently about the relationship between dependers and the packages they depend on.

So instead of using that `foo 2.0.0` directly, it needs to be converted into a range, which would be `foo >=2.0.0` here as `2.0.0` is the last available version of `foo`. This range is then used as first Term of `depIncompats`.

**Comment by mpizenberg** [comment]
I'll check that this weekend but the first thing coming to mind is that merging incompatibility ranges is only a matter of efficiency and should not change the behavior

**Comment by malaire** [comment]
One interesting consequence of this is when you can change from single version to any version. For example just before Example 3 fails elm-pubgrub uses `bar 1.0.0` as first Term instead of `bar any` as it should be. I havn't checked this fully yet, but this can be significant.

**Comment by mpizenberg** [comment]
The `any` you mention makes me think of that question I asked a while ago to Pub maintainers: https://github.com/dart-lang/pub/issues/2485 where I was wondering how to categorize some incompatibilities. Just had an answer yesterday and didn't take time to process yet but maybe it's related?

**Comment by malaire** [comment]
Reading about Step 9 of [this Example 3](https://github.com/dart-lang/pub/blob/master/doc/solver.md#performing-conflict-resolution), a key point there is that `{bar ^1.0.0}` satisfies `bar any`, i.e. when `{bar ^1.0.0}` is true, `bar any` must also be true.

Now if you have `bar 1.0.0` instead of `bar any`, that doesn't hold anymore. `{bar ^1.0.0}` being true doesn't imply that `bar` is exacly `1.0.0` UNLESS of course `1.0.0` is the only version in that range.

In Example 3 it is the only version, but I don't see `PubGrub.conflictResolution` accessing `Stub.listAvailableVersions` so that it can know that in this case `{bar ^1.0.0}` does satisfy `bar 1.0.0` even through generally that would not be so.

**Comment by malaire** [comment]
Even though the PR that created this issue was closed as incorrect, I think it's worth checking whether `bar any` case is handled correctly here.

Referring to my comment above, I think algorithm can work correctly without expanding version ranges, but only if it uses the list of available versions to correctly check relations.

That check is done by `PartialSolution.relation` and `Incompatibility.relation`, and trying to follow the algorithm I don't see it accessing list of available versions anywhere, so I can't see how it can work correctly with non-expanded versions?

EDIT: For conflict resolution actually `Term.satisfies` seems to be the function which checks relations. It doesn't seem to access list of available versions either.

**Comment by mpizenberg** [comment]
Yep definitely worth checking. Also I think now that I've had a month break from this, a second re-read of the whole thing this weekend will do some good (crossing fingers).
